[package]
name = "msg"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
msg-socket.workspace = true
msg-transport.workspace = true
msg-wire.workspace = true

tokio.workspace = true
bytes.workspace = true
