[package]
name = "msg"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
msg-socket.workspace = true
msg-transport.workspace = true
msg-wire.workspace = true

tokio.workspace = true
bytes.workspace = true
tokio-stream.workspace = true

[dev-dependencies]
# benchmarking
tracing-subscriber = "0.3"
futures.workspace = true
tracing.workspace = true
rand.workspace = true

[[bench]]
name = "req_res_localhost"
harness = false
