[package]
name = "msg-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
path = "msg/src/lib.rs"

[workspace]
members = ["msg-socket", "msg-wire", "msg-transport"]

[workspace.dependencies]
msg-wire = { path = "./msg-wire" }
msg-socket = { path = "./msg-socket" }
msg-transport = { path = "./msg-transport" }

# async
async-trait = "0.1"
tokio = { version = "1", features = ["full"] }
tokio-util = { version = "0.7", features = ["codec"] }
futures = "0.3"
tokio-stream = "0.1"

bytes = "1"
thiserror = "1"
tracing = "0.1"

# performance
rustc-hash = "1"
